#!/bin/bash
for file in $(ls -a); do if [ "$file" = "." ]; then echo "$file/"; elif [ "$file" = ".." ]; then echo "$file/"; elif [ -d "$file" ]; then echo "$file/"; else echo "$file"; fi; done | sort -k1.1,1.1 -k1.2 | tr '\n' ', ' | sed 's/,$/\n/'
