#!/bin/bash
ls -a | while read -r line; do [[ $line == "." ]] && echo "$line/"; [[ $line == ".." ]] && echo "$line/"; [[ -d $line ]] && echo "${line}/"; [[ ! -d $line ]] && echo "$line"; done | sort -k1.1,1.1 -k1.2 | tr '\n' ', ' | sed 's/,$/\n/'
